<MainScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: '50dp'
        spacing: '30dp'
        MDIconButton:
            icon: "cog"
            pos_hint: {"right": 1, "top": 1}
            icon_size: '50dp'

            on_press:
                root.manager.current = 'settings'
        MDLabel:
            text: "SHUTER"
            halign: 'center'
            font_size: '60sp'
        # Image:
        #     source: 'assets/images/rocket.png'
        #     size_hint_y: 0.7
        #     allow_stretch: True

        MDIconButton:
            icon: "play"
            font_size: '60sp'
            pos_hint: {'center_x': 0.5,'center_y': 0.5}
            # theme_text_color: "Custom"
            # text_color: "white"
            # line_color: "red"
            on_press:
                root.manager.current = 'game'

<GameScreen>:
    FloatLayout:
        FloatLayout:
            id: game
            FloatLayout:
                id: back
            FloatLayout:
                id: front
                # Ship:
                #     id: ship
                #     center: root.center

        FloatLayout:
            id: interface

<SettingsScren>:
    MDBoxLayout:
        orientation: 'horizontal'
        padding: '40dp'
        spacing: '20dp'

        MDLabel:
            text: "Settings"
            halign: 'center'
            font_size: '60sp'

        MDIconButton:
            icon: "home"
            font_size: '70sp'
            pos_hint: {'center_x': 0.5,'center_y': 0.5}

            on_press:
                root.manager.current = 'main'
